### ISSUE TITLE
KeyError: 'stretch-backports'

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/appimagelint#4]
```
linux@localhost:~> Downloads/appimagelint-x86_64.AppImage /isodevice/Applications/Firefox-66.0.5.glibc2.4-x86_64.AppImage 
appimagelint.cli[6028] [INFO] Checking AppImage /isodevice/Applications/Firefox-66.0.5.glibc2.4-x86_64.AppImage
appimagelint.cli[6028] [INFO] Running check "GNU libc ABI check"
appimagelint.glibc_abi_check[6028] [INFO] detected required version for runtime: 2.3.3
appimagelint.glibc_abi_check[6028] [INFO] detected required version for payload: 2.12
appimagelint.cache[6028] [INFO] Fetching glibc version data for debian
appimagelint.setup[6028] [INFO] Fetching glibc package versions from Debian sources API
appimagelint.glibc_abi_check[6028] [INFO] [✔] AppImage can run on Debian oldstable (jessie)
appimagelint.glibc_abi_check[6028] [WARNING] could not find version for stable, trying backports
Traceback (most recent call last):
  File "/tmp/.mount_appimawGw5X2/usr/conda/lib/python3.7/site-packages/appimagelint/checks/gnu_abi_check_base.py", line 103, in _check_debian_compat
    max_supported_version = versions_map[codename]
KeyError: 'stretch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_appimawGw5X2/usr/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/tmp/.mount_appimawGw5X2/usr/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_appimawGw5X2/usr/conda/lib/python3.7/site-packages/appimagelint/__main__.py", line 4, in <module>
    run()
  File "/tmp/.mount_appimawGw5X2/usr/conda/lib/python3.7/site-packages/appimagelint/cli.py", line 96, in run
    for testres in check.run():
  File "/tmp/.mount_appimawGw5X2/usr/conda/lib/python3.7/site-packages/appimagelint/checks/gnu_abi_check_base.py", line 76, in run
    for result in self._check_debian_compat(required_version):
  File "/tmp/.mount_appimawGw5X2/usr/conda/lib/python3.7/site-packages/appimagelint/checks/gnu_abi_check_base.py", line 106, in _check_debian_compat
    max_supported_version = versions_map["{}-backports".format(codename)]
KeyError: 'stretch-backports'

linux@localhost:~> cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="15.1 "
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.1"
PRETTY_NAME="openSUSE Leap 15.1"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.1"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```

**Comment by TheAssassin** [comment]
Cannot reproduce in Tumbleweed, but I will improve the robustness of the code in question. There will further be a "could not run / crashed / ..." test result state.

**Comment by probonopd** [comment]
This we ran on Leap, not Tumbleweed, which is expected to be even better tested and hence to have less than zero bugs ;-)

**Comment by TheAssassin** [comment]
We're depending on some Debian APIs and endpoints, so this might've been a temporary issue. As said, I cannot reproduce this any more. But given the traceback, I can improve the robustness to avoid such issues in the future. Think of it as a preventive measure.

**Comment by probonopd** [comment]
Yes, seems to be working now.

**Comment by TheAssassin** [comment]
Wrongly reported as new issue (#6):

```
me@host:~$ /home/me/Downloads/appimagelint-x86_64.AppImage /home/me/Downloads/Mumble-427b148-x86_64.AppImage 
appimagelint.cli[13896] [INFO] Checking AppImage /home/me/Downloads/Mumble-427b148-x86_64.AppImage
appimagelint.cli[13896] [INFO] Running check "GNU libc ABI check"
appimagelint.glibc_abi_check[13896] [INFO] detected required version for runtime: 2.3.3
appimagelint.glibc_abi_check[13896] [INFO] detected required version for payload: 2.17
appimagelint.glibc_abi_check[13896] [WARNING] could not find version for oldstable, trying backports
appimagelint.glibc_abi_check[13896] [INFO] [✔] AppImage can run on Debian oldstable (jessie)
appimagelint.glibc_abi_check[13896] [INFO] [✔] AppImage can run on Debian stable (stretch)
appimagelint.glibc_abi_check[13896] [WARNING] could not find version for testing, trying backports
Traceback (most recent call last):
  File "/tmp/.mount_appimahLFmu9/usr/conda/lib/python3.7/site-packages/appimagelint/checks/gnu_abi_check_base.py", line 103, in _check_debian_compat
    max_supported_version = versions_map[codename]
KeyError: 'buster'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_appimahLFmu9/usr/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/tmp/.mount_appimahLFmu9/usr/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_appimahLFmu9/usr/conda/lib/python3.7/site-packages/appimagelint/__main__.py", line 4, in <module>
    run()
  File "/tmp/.mount_appimahLFmu9/usr/conda/lib/python3.7/site-packages/appimagelint/cli.py", line 96, in run
    for testres in check.run():
  File "/tmp/.mount_appimahLFmu9/usr/conda/lib/python3.7/site-packages/appimagelint/checks/gnu_abi_check_base.py", line 76, in run
    for result in self._check_debian_compat(required_version):
  File "/tmp/.mount_appimahLFmu9/usr/conda/lib/python3.7/site-packages/appimagelint/checks/gnu_abi_check_base.py", line 106, in _check_debian_compat
    max_supported_version = versions_map["{}-backports".format(codename)]
KeyError: 'buster-backports'
me@host:~$ /home/me/Downloads/appimagelint-x86_64.AppImage /home/me/Downloads/
appimagelint-x86_64.AppImage     micropad-3.18.1-x86_64.AppImage  Mumble-83bca04-x86_64.AppImage   outer_wall2.stl                  screw2.stl                       
Fanny_Pocket.stl                 Mumble-427b148-x86_64.AppImage   Mumble-b5a0b79-x86_64.AppImage   satisfying-twister.scad          Wallet_All_Parts.stl             
inner.stl                        Mumble-5ffa1a4-x86_64.AppImage   outer.stl                        satisfying-twister.stl           Wallet.stl                       
me@host:~$ /home/me/Downloads/appimagelint-x86_64.AppImage /home/me/Downloads/appimagelint-x86_64.AppImage 
appimagelint.cli[14037] [INFO] Checking AppImage /home/me/Downloads/appimagelint-x86_64.AppImage
appimagelint.cli[14037] [INFO] Running check "GNU libc ABI check"
appimagelint.glibc_abi_check[14037] [INFO] detected required version for runtime: 2.3.3
appimagelint.glibc_abi_check[14037] [INFO] detected required version for payload: 2.14
appimagelint.glibc_abi_check[14037] [WARNING] could not find version for oldstable, trying backports
appimagelint.glibc_abi_check[14037] [INFO] [✔] AppImage can run on Debian oldstable (jessie)
appimagelint.glibc_abi_check[14037] [INFO] [✔] AppImage can run on Debian stable (stretch)
appimagelint.glibc_abi_check[14037] [WARNING] could not find version for testing, trying backports
Traceback (most recent call last):
  File "/tmp/.mount_appima1kePO9/usr/conda/lib/python3.7/site-packages/appimagelint/checks/gnu_abi_check_base.py", line 103, in _check_debian_compat
    max_supported_version = versions_map[codename]
KeyError: 'buster'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_appima1kePO9/usr/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/tmp/.mount_appima1kePO9/usr/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_appima1kePO9/usr/conda/lib/python3.7/site-packages/appimagelint/__main__.py", line 4, in <module>
    run()
  File "/tmp/.mount_appima1kePO9/usr/conda/lib/python3.7/site-packages/appimagelint/cli.py", line 96, in run
    for testres in check.run():
  File "/tmp/.mount_appima1kePO9/usr/conda/lib/python3.7/site-packages/appimagelint/checks/gnu_abi_check_base.py", line 76, in run
    for result in self._check_debian_compat(required_version):
  File "/tmp/.mount_appima1kePO9/usr/conda/lib/python3.7/site-packages/appimagelint/checks/gnu_abi_check_base.py", line 106, in _check_debian_compat
    max_supported_version = versions_map["{}-backports".format(codename)]
KeyError: 'buster-backports'

```

**Comment by TheAssassin** [comment]
That specific bug cannot occur any more in the latest version of the source code, see https://github.com/TheAssassin/appimagelint/blob/7c2ba7e2c0d83d50951fc46699fb4577dedacbee/appimagelint/checks/gnu_abi_check_base.py#L100-L115. All possibly occurring `KeyError`s are handled correctly.

As you correctly stated in this issue, there's a lack of version identifiers for the AppImages uploaded to GitHub releases. Fixing that now. But really, the latest version cannot error out like that, that line referred to in your bug report doesn't even exist like that any more since https://github.com/TheAssassin/appimagelint/commit/8b57394fe5fc1d0b08e37ce015498f901cd09237...

**Comment by TheAssassin** [comment]
Travis build had been broken, so the fix didn't reach you. Has been fixed lately. Please retry.
